# Generated by Django 2.2.11 on 2020-09-06 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Desarrollo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineaBase',
            fields=[
                ('Codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=255)),
                ('Estado', models.CharField(blank=True, choices=[('i', 'Iniciado'), ('p', 'Pendiente'), ('f', 'Finalizado')], default='p', help_text='Estados de la Tarea', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=255)),
                ('Estado', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=255)),
                ('prioridad', models.CharField(max_length=255)),
                ('estado', models.CharField(blank=True, choices=[('i', 'Iniciado'), ('p', 'Pendiente'), ('f', 'Finalizado')], default='p', help_text='Estados de la Tarea', max_length=1)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('observacion', models.CharField(blank=True, max_length=255, null=True)),
                ('linea_base', models.ForeignKey(blank=True, help_text='Linea Base a la que pertence', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Desarrollo.LineaBase')),
                ('proyecto', models.ForeignKey(blank=True, help_text='Proyecto al que pertence', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Desarrollo.Proyecto')),
                ('tarea_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Desarrollo.Tarea')),
            ],
        ),
        migrations.DeleteModel(
            name='Desarrollo',
        ),
    ]
