# Generated by Django 3.0.3 on 2020-04-02 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Desarrollo', '0002_auto_20200401_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='estado',
            field=models.CharField(blank=True, choices=[('i', 'Iniciado'), ('p', 'Pendiente'), ('f', 'Finalizado')], default='p', help_text='Estados de la Tarea', max_length=1),
        ),
    ]
