# Generated by Django 3.0.3 on 2020-08-30 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Desarrollo', '0003_auto_20200402_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='proyecto',
            field=models.ForeignKey(blank=True, help_text='Proyecto al que pertence', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Desarrollo.Proyecto'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='tarea_padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Desarrollo.Tarea'),
        ),
    ]
