# Generated by Django 2.2.11 on 2020-09-06 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineaBase',
            fields=[
                ('Codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=255)),
                ('Estado', models.CharField(blank=True, choices=[('i', 'Iniciado'), ('p', 'Pendiente'), ('f', 'Finalizado')], default='p', help_text='Estados de la Tarea', max_length=1)),
            ],
        ),
    ]
