# Generated by Django 2.2.11 on 2020-09-06 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Desarrollo', '0003_auto_20200906_2157'),
        ('Configuracion', '0002_lineabase'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineabase',
            name='tareas',
            field=models.ManyToManyField(to='Desarrollo.Tarea'),
        ),
    ]
