# Generated by Django 3.0.3 on 2020-10-05 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Desarrollo', '0005_auto_20200906_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='linea_base',
        ),
        migrations.DeleteModel(
            name='LineaBase',
        ),
    ]
