# Generated by Django 3.0.3 on 2020-10-05 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Configuracion', '0002_lineabase'),
        ('Desarrollo', '0006_auto_20201005_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='linea_base',
            field=models.ForeignKey(blank=True, help_text='Linea Base a la que pertence', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Configuracion.LineaBase'),
        ),
    ]
